openapi: 3.0.0
servers:
  - url: 'https://api.mpsa.com/api/connectedcar/v2'
info:
  version: '2.0'
  title: Groupe PSA Connected Car API
  description: >
    *PSA B2C Connected Car API*
    
   
    # Introduction

    This is the description of the *Groupe PSA Connected Car V2 API*. The
    speccification is  is based on **OpenAPI Specification version 3** and can be displayed via [ReDoc](https://github.com/Rebilly/ReDoc)a or
    [Swagger](http://swagger.io).
      This API allows applications to fetch data from the connected Vehicles data platform.
    # Authentication

    PSA Connected Car APIs uses the [OAuth
    2.0](https://tools.ietf.org/html/rfc6749) protocol for authentication and
    authorization. any application require a valid [Access
    Token](https://tools.ietf.org/html/rfc6749#section-1.4) to access to user
    data.
    
    # Errors:
      Error codes returned by all REST APIs comply with the standard. Nevertheless, PSA Services (callers) need to have more complete data structures (even when the answer is not Http-OK) to better detail the type of error by providing application code, message and a debugging code(for investigation purposes). The http code of the response is managed by the protocol itself (in the header).
      
      **Errors are  returned as a generic error response:**
       * ```xError``` object model.    
  license:
    name: Groupe PSA Licence
    url: 'https://www.psa-peugeot-citroen.com/'
tags:
  - name: User
  - name: Vehicles
    description: Access to Vehicles details.
  - name: Trips
    description: Describe Trips of a a User or Vehicle
paths:
  /user:
    get:
      tags:
        - User
      summary: User's information
      description: Returns the User's information.
      operationId: getUser
  /user/vehicles:
    get:
      tags:
        - Vehicles
      summary: List of vehicules
      description: Returns the Vehicles associated with the User.
      operationId: getVehiclesByDevice
      security:
        - Vehicle_auth:
            - Vehicle_read
  '/user/vehicles/{id}':
    get:
      tags:
        - Vehicles
      summary: Details of vehicule
      description: Returns detailed information about a Vehicle.
      operationId: getVehicleByid
      security:
        - Vehicle_auth:
            - Vehicle_read
  '/user/vehicles/{id}/telemetry':
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Vehicles
      description: >-
        Returns the latest Telemetry messages that occurred during a selective
        timestamp-ranges and bounded by an index range.
      operationId: getTelemetry
      security:
        - Vehicle_auth:
            - Telemetry_read
            - Vehicle_read
  '/user/vehicles/{id}/lastPosition':
    get:
      tags:
        - Vehicles
      summary: Last position identified
      description: Returns the latest GPS Position of the Vehicle.
      operationId: getCarLastPosition
      security:
        - Vehicle_auth:
            - localisation_read
            - Vehicle_read
  '/user/vehicles/{id}/collisions':
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Vehicles
      description: >-
        Returns the set of Collisions that occurred for a given vehicle (id)
        during the timestamp ranges and bounded by an index range.
      operationId: getVehicleCollision
      security:
        - Vehicle_auth:
            - Collision_read
            - Vehicle_read
  '/user/vehicles/{id}/collisions/{cid}':
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Vehicles
      description: Returns the Collision that matches the vehicle id and the Collision cid.
      operationId: getVehicleCollisionById
      security:
        - Vehicle_auth:
            - Collision_read
            - Vehicle_read
  '/user/vehicles/{id}/maintenance':
    get:
      tags:
        - Vehicles
      description: Returns the latest Maintenance information for a Vehicle.
      operationId: getVehicleMaintenance
      security:
        - Vehicle_auth:
            - Maintenance_read
            - Vehicle_read
  '/user/vehicles/{id}/status':
    get:
      tags:
        - Vehicles
      description: Returns the latest vehicle status.
      summary: Vehicle status.
      operationId: getVehicleStatus
      security:
        - Vehicle_auth:
            - Status_read
            - Vehicle_read
  '/user/vehicles/{id}/alerts':
    get:
      tags:
        - Vehicles
      description: Returns the latest alert messages for a Vehicle.
      operationId: getVehicleAlerts
      security:
        - Vehicle_auth:
            - alert_read
            - Vehicle_read
  '/user/vehicles/{id}/alerts/{aid}':
    get:
      tags:
        - Vehicles
      description: Returns information about a specific alert messages for a Vehicle.
      operationId: getVehicleAlertsById
      security:
        - Vehicle_auth:
            - alert_read
            - Vehicle_read
  '/user/vehicles/{id}/monitors':
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Vehicles
      description: Returns the list of subscribed Monitors for a Vehicle.
      operationId: getVehicleMonitors
    post:
      deprecated: true
      tags:
        - Vehicles
      summary: Create a new Monitor. OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      description: |
                    >Create a Monitor for a Vehicle. This is a kind of vehicle monitor that generates an event following the transition state of one of the (monitored) data  of the vehicles. As for example the fuel level, the moving out of a defined geographical area. 
                    
                    >When the the trigger occurs, the built event expressed as a JSON object will be sent over the callback.
      operationId: setVehicleMonitor
      security:
        - Vehicle_auth:
            - Vehicle_read
            - Monitor_write
  '/user/vehicles/{id}/monitors/{mid}':
    put:
      deprecated: true
      tags:
        - Vehicles
      summary: Update and existing Monitor. OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      description: |
                    Update an existing ```Monitor``` that has been posted (and accepted previously) for this vehicle. The monitor object (body) provided should be complete because the aggregation is not supported for the update of the ```monitor```. you can retrieve this object using the ```GET /monitor/{mid}``` API then modify it and finally publish it (via this ```PUT API```) 
      operationId: updateFleetVehicleMonitor
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Vehicles
      description: Returns information about a specific Monitor for a Vehicle.
      operationId: getVehicleMonitorsById
      security:
        - Vehicle_auth:
            - Monitor_read
            - Vehicle_read
    delete:
      deprecated: true
      tags:
        - Vehicles
      summary: Delete a Monitor. OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      description: Stop (disable) an existing Monitor.
      operationId: deleteMonitordd
      security:
        - Vehicle_auth:
            - Vehicle_read
            - Monitor_write
  '/user/vehicles/{id}/monitors/{mid}/status': 
    put:
      deprecated: true
      tags:
        - Vehicles
      summary: Set a new monitor status. OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      description: |
                   Set monitor status. 
      operationId: setFleetVehicleMonitorStatus
  '/user/trips':
    $ref: '#/x-fragment/User_Trips_getter'
  '/user/trips/{tid}':
    $ref: '#/x-fragment/User_Trip_id_getter'
  '/user/trips/{tid}/ecoaching':
    $ref: '#/x-fragment/User_Trip_id_ECoaching_getter'
  '/user/trips/{tid}/alerts':
    $ref: '#/x-fragment/User_Trip_id_Alerts_getter'
  '/user/trips/{tid}/alerts/{aid}':
    $ref: '#/x-fragment/User_Trip_id_Alerts_id_getter'
  '/user/trips/{tid}/collisions':
    $ref: '#/x-fragment/User_Trip_id_Collisions_getter'
  '/user/trips/{tid}/collisions/{cid}':
    $ref: '#/x-fragment/User_Trip_id_Collisions_id_getter'
  '/user/trips/{tid}/wayPoints':
    $ref: '#/x-fragment/User_Trip_id_wayPoints_getter'
  '/user/trips/{tid}/telemetry':
    $ref: '#/x-fragment/User_Trip_id_Telemetry_getter'
  '/user/vehicles/{id}/trips':
    $ref: '#/x-fragment/Vehicle_id_Trips'
  '/user/vehicles/{id}/trips/{tid}':
    $ref: '#/x-fragment/Vehicle_id_Trip_id'
  '/user/vehicles/{id}/trips/{tid}/ecoaching':
    $ref: '#/x-fragment/Vehicle_id_Trip_id_ECoaching_getter'
  '/user/vehicles/{id}/trips/{tid}/alerts':
    $ref: '#/x-fragment/Vehicle_id_Trip_id_Alerts_getter'
  '/user/vehicles/{id}/trips/{tid}/alerts/{aid}':
    $ref: '#/x-fragment/Vehicle_id_Trip_id_Alerts_id_getter'
  '/user/vehicles/{id}/trips/{tid}/collisions':
    $ref: '#/x-fragment/Vehicle_id_Trip_id_Collisions_getter'
  '/user/vehicles/{id}/trips/{tid}/collisions/{cid}':
    $ref: '#/x-fragment/Vehicle_id_Trip_id_Collisions_id_getter'
  '/user/vehicles/{id}/trips/{tid}/wayPoints':
    $ref: '#/x-fragment/Vehicle_id_Trip_id_wayPoints_getter'
  '/user/vehicles/{id}/trips/{tid}/telemetry':
    $ref: '#/x-fragment/Vehicle_id_Trip_id_Telemetry_getter'
 
components:
  securitySchemes:
    Vehicle_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://api.mpsa.com/api/connectedcar/v2/oauth/authorize'
          scopes:
            localisation_read: read location related data
            Telemetry_read: read Telemetry related data
            Maintenance_read: read Maintenance related data
            Collision_read: read Collision related data
            Trip_read: read Trip related data
            alert_read: read alert related data
            alert_write: 'create, modify or delete alerte'
            Vehicle_read: read Vehicle related data
            Status_read: read Vehicle related status
#    sampling:
#      name: sampling.
 #     in: query
#      description: >
#        Sampling of returned waypoints. the read sampling expresses number of
#        vehicle's read position time cycle (seconds)between to aquisition.
#      required: false
#      schema:
#        type: integer
x-fragment:
  User_Trip_id_Telemetry_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: >-
        Returns the set of Telemetry values that occurred for a given vehicle
        (id) and a speific Trip (tid) during the timestamp ranges and bounded by
        an index range.
      operationId: getTelemetryForTrip
      security:
        - Vehicle_auth:
            - Trip_read
  User_Trip_id_wayPoints_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: Gives the wayPoints for a specified User Trip.
      operationId: getPathForTrip
      security:
        - Vehicle_auth:
            - Trip_read
  User_Trip_id_Collisions_id_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: >-
        Returns the Collision(cid) that occurred for a given vehicle(id) during
        a Trip(tid) .
      operationId: getUserCollisionByTipById
      security:
        - Vehicle_auth:
            - Collision_read
            - Trip_read
  User_Trip_id_Collisions_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: >-
        Returns the set of Collisions that occurred for a given vehicle (id) and
        a speific Trip (tid) during the timestamp ranges and bounded by an index
        range.
      operationId: getUserCollisionsByTripId
      security:
        - Vehicle_auth:
            - Collision_read
            - Trip_read
  User_Trip_id_Alerts_id_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: Returns information about a specific alert messages for a given Trip.
      operationId: getUserTripAlertByAid
      security:
        - Vehicle_auth:
            - alert_read
            - Trip_read
  User_Trip_id_Alerts_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: Returns the latest alert messages during a Trip.
      operationId: getUserTripAlerts
      security:
        - Vehicle_auth:
            - alert_read
            - Trip_read
  Vehicle_id_Trip_id_Telemetry_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: >-
        Returns the set of Telemetry values that occurred for a given vehicle
        (id) and a speific Trip (tid) during the timestamp ranges and bounded by
        an index range.
      operationId: getTelemetryForTrip
      security:
        - Vehicle_auth:
            - Trip_read
  Vehicle_id_Trip_id_wayPoints_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: Gives the Vehicle's wayPoints for a specified Trip.
      operationId: getPathForTrip
      security:
        - Vehicle_auth:
            - Trip_read
  Vehicle_id_Trip_id_Collisions_id_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: >-
        Returns the Collision(cid) that occurred for a given vehicle(id) during
        a Trip(tid) .
      operationId: getVehicleCollisionByTipById
      security:
        - Vehicle_auth:
            - Collision_read
            - Vehicle_read
            - Trip_read
  Vehicle_id_Trip_id_Collisions_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: >-
        Returns the set of Collisions that occurred for a given vehicle (id) and
        a speific Trip (tid) during the timestamp ranges and bounded by an index
        range.
      operationId: getVehicleCollisionsByTripId
      security:
        - Vehicle_auth:
            - Collision_read
            - Vehicle_read
            - Trip_read
  Vehicle_id_Trip_id_Alerts_id_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: >-
        Returns information about a specific alert messages for a given Vehicle
        and Trip.
      operationId: getVehicleTripAlertByAid
      security:
        - Vehicle_auth:
            - alert_read
            - Vehicle_read
            - Trip_read
  Vehicle_id_Trip_id_Alerts_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: Returns the latest alert messages for a Vehicle.
      operationId: getVehicleTripAlerts
      security:
        - Vehicle_auth:
            - alert_read
            - Vehicle_read
            - Trip_read
  User_Trip_id_ECoaching_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: Return the User Trip ECoaching evaluation.
      operationId: getTripsByVehicle
      security:
        - Vehicle_auth:
            - Trip_read
  Vehicle_id_Trip_id_ECoaching_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: Return the Trip ECoaching evaluation.
      operationId: getTripsByVehicle
      security:
        - Vehicle_auth:
            - Trip_read
            - Vehicle_read
  User_Trip_id_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: >-
        This method returns the Trip that matches the Trip id (tid) User has
        taken.
      operationId: getTripsByVehicle
      security:
        - Vehicle_auth:
            - Trip_read
  Vehicle_id_Trip_id:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: >-
        This method returns the Trip that matches the Trip id (tid) a given
        Vehicle (id) has taken.
      operationId: getTripByVehicle
      security:
        - Vehicle_auth:
            - Trip_read
            - Vehicle_read
  Vehicle_id_Trips:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: >-
        This method returns a list of all Trips that a given Vehicle has taken.
        This will NOT include Trips that have not yet been completed.
      operationId: getTripsByVehicle
      security:
        - Vehicle_auth:
            - Trip_read
            - Vehicle_read
  User_Trips_getter:
    get:
      deprecated: true
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
      tags:
        - Trips
      description: >-
        This method returns a list of all Trips the User has taken. This will
        NOT include Trips that have not yet been completed.
      operationId: getUserTrips
      security:
        - Vehicle_auth:
            - Trip_read
  general_error_fragment:
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/xError'
