swagger: '2.0'
info:
  description: >
    *PSA B2C Connected Car API*


    # Introduction

    This is the description of the *Groupe PSA Connected Car V2 API*. The
    speccification is  is based on **OpenAPI Specification version 3** and can
    be displayed via [ReDoc](https://github.com/Rebilly/ReDoc)a or
    [Swagger](http://swagger.io).
      This API allows applications to fetch data from the connected Vehicles data platform.
    # Authentication

    PSA Connected Car APIs uses the [OAuth
    2.0](https://tools.ietf.org/html/rfc6749) protocol for authentication and
    authorization. any application require a valid [Access
    Token](https://tools.ietf.org/html/rfc6749#section-1.4) to access to user
    data.

    # Errors
      Error codes returned by all REST APIs comply with the standard. Nevertheless, PSA Services (callers) need to have more complete data structures (even when the answer is not Http-OK) to better detail the type of error by providing application code, message and a debugging code(for investigation purposes). The http code of the response is managed by the protocol itself (in the header).
      
      **Errors are  returned as a generic error response:**
       * ```xError``` object model.    
  license:
    name: Groupe PSA Licence
    url: 'https://www.psa-peugeot-citroen.com/'
  title: Groupe PSA Connected Car - WEB API B2C
  version: '4.0'
host: api.groupe-psa.com/
basePath: connectedcar/v4
schemes:
  - https
paths:
  /user:
    get:
      tags:
        - User
      description: Returns the User's information.
      operationId: getUser
      summary: User's information
  /user/trips:
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        This method returns a list of all Trips the User has taken. This will
        NOT include Trips that have not yet been completed.
      operationId: getUserTrips
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/trips/{tid}':
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        This method returns the Trip that matches the Trip id (tid) User has
        taken.
      operationId: getTripsByVehicle
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/trips/{tid}/alerts':
    get:
      security:
        - Vehicle_auth:
            - alert_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: Returns the latest alert messages during a Trip.
      operationId: getUserTripAlerts
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/trips/{tid}/alerts/{aid}':
    get:
      security:
        - Vehicle_auth:
            - alert_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: Returns information about a specific alert messages for a given Trip.
      operationId: getUserTripAlertByAid
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/trips/{tid}/collisions':
    get:
      security:
        - Vehicle_auth:
            - Collision_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns the set of Collisions that occurred for a given vehicle (id) and
        a speific Trip (tid) during the timestamp ranges and bounded by an index
        range.
      operationId: getUserCollisionsByTripId
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/trips/{tid}/collisions/{cid}':
    get:
      security:
        - Vehicle_auth:
            - Collision_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns the Collision(cid) that occurred for a given vehicle(id) during
        a Trip(tid) .
      operationId: getUserCollisionByTipById
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/trips/{tid}/ecoaching':
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: Return the User Trip ECoaching evaluation.
      operationId: getTripsByVehicle
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/trips/{tid}/telemetry':
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns the set of Telemetry values that occurred for a given vehicle
        (id) and a speific Trip (tid) during the timestamp ranges and bounded by
        an index range.
      operationId: getTelemetryForTrip
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/trips/{tid}/wayPoints':
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: Gives the wayPoints for a specified User Trip.
      operationId: getPathForTrip
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  /user/vehicles:
    get:
      security:
        - Vehicle_auth:
            - Vehicle_read
      tags:
        - Vehicles
      description: Returns the Vehicles associated with the User.
      operationId: getVehiclesByDevice
      summary: List of vehicules
  '/user/vehicles/{id}':
    get:
      security:
        - Vehicle_auth:
            - Vehicle_read
      tags:
        - Vehicles
      description: Returns detailed information about a Vehicle.
      operationId: getVehicleByid
      summary: Details of vehicule
  '/user/vehicles/{id}/alerts':
    get:
      security:
        - Vehicle_auth:
            - alert_read
            - Vehicle_read
      tags:
        - Vehicles
      description: Returns the latest alert messages for a Vehicle.
      operationId: getVehicleAlerts
  '/user/vehicles/{id}/alerts/{aid}':
    get:
      security:
        - Vehicle_auth:
            - alert_read
            - Vehicle_read
      tags:
        - Vehicles
      description: Returns information about a specific alert messages for a Vehicle.
      operationId: getVehicleAlertsById
  '/user/vehicles/{id}/collisions':
    get:
      security:
        - Vehicle_auth:
            - Collision_read
            - Vehicle_read
      tags:
        - Vehicles
      deprecated: true
      description: >-
        Returns the set of Collisions that occurred for a given vehicle (id)
        during the timestamp ranges and bounded by an index range.
      operationId: getVehicleCollision
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/collisions/{cid}':
    get:
      security:
        - Vehicle_auth:
            - Collision_read
            - Vehicle_read
      tags:
        - Vehicles
      deprecated: true
      description: Returns the Collision that matches the vehicle id and the Collision cid.
      operationId: getVehicleCollisionById
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/lastPosition':
    get:
      security:
        - Vehicle_auth:
            - localisation_read
            - Vehicle_read
      tags:
        - Vehicles
      description: Returns the latest GPS Position of the Vehicle.
      operationId: getCarLastPosition
      summary: Last position identified
  '/user/vehicles/{id}/maintenance':
    get:
      security:
        - Vehicle_auth:
            - Maintenance_read
            - Vehicle_read
      tags:
        - Vehicles
      description: Returns the latest Maintenance information for a Vehicle.
      operationId: getVehicleMaintenance
  '/user/vehicles/{id}/monitors':
    get:
      tags:
        - Vehicles
      deprecated: true
      description: Returns the list of subscribed Monitors for a Vehicle.
      operationId: getVehicleMonitors
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
    post:
      security:
        - Vehicle_auth:
            - Vehicle_read
            - Monitor_write
      tags:
        - Vehicles
      deprecated: true
      description: >
        >Create a Monitor for a Vehicle. This is a kind of vehicle monitor that
        generates an event following the transition state of one of the
        (monitored) data  of the vehicles. As for example the fuel level, the
        moving out of a defined geographical area. 


        >When the the trigger occurs, the built event expressed as a JSON object
        will be sent over the callback.
      operationId: setVehicleMonitor
      summary: Create a new Monitor. OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/monitors/{mid}':
    delete:
      security:
        - Vehicle_auth:
            - Vehicle_read
            - Monitor_write
      tags:
        - Vehicles
      deprecated: true
      description: Stop (disable) an existing Monitor.
      operationId: deleteMonitordd
      summary: Delete a Monitor. OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
    get:
      security:
        - Vehicle_auth:
            - Monitor_read
            - Vehicle_read
      tags:
        - Vehicles
      deprecated: true
      description: Returns information about a specific Monitor for a Vehicle.
      operationId: getVehicleMonitorsById
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
    put:
      tags:
        - Vehicles
      deprecated: true
      description: >
        Update an existing ```Monitor``` that has been posted (and accepted
        previously) for this vehicle. The monitor object (body) provided should
        be complete because the aggregation is not supported for the update of
        the ```monitor```. you can retrieve this object using the ```GET
        /monitor/{mid}``` API then modify it and finally publish it (via this
        ```PUT API```) 
      operationId: updateFleetVehicleMonitor
      summary: Update and existing Monitor. OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/monitors/{mid}/status':
    put:
      tags:
        - Vehicles
      deprecated: true
      description: |
        Set monitor status. 
      operationId: setFleetVehicleMonitorStatus
      summary: Set a new monitor status. OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/status':
    get:
      security:
        - Vehicle_auth:
            - Status_read
            - Vehicle_read
      tags:
        - Vehicles
      description: Returns the latest vehicle status.
      operationId: getVehicleStatus
      summary: Vehicle status.
  '/user/vehicles/{id}/telemetry':
    get:
      security:
        - Vehicle_auth:
            - Telemetry_read
            - Vehicle_read
      tags:
        - Vehicles
      deprecated: true
      description: >-
        Returns the latest Telemetry messages that occurred during a selective
        timestamp-ranges and bounded by an index range.
      operationId: getTelemetry
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/trips':
    get:
      security:
        - Vehicle_auth:
            - Trip_read
            - Vehicle_read
      tags:
        - Trips
      deprecated: true
      description: >-
        This method returns a list of all Trips that a given Vehicle has taken.
        This will NOT include Trips that have not yet been completed.
      operationId: getTripsByVehicle
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/trips/{tid}':
    get:
      security:
        - Vehicle_auth:
            - Trip_read
            - Vehicle_read
      tags:
        - Trips
      deprecated: true
      description: >-
        This method returns the Trip that matches the Trip id (tid) a given
        Vehicle (id) has taken.
      operationId: getTripByVehicle
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/trips/{tid}/alerts':
    get:
      security:
        - Vehicle_auth:
            - alert_read
            - Vehicle_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: Returns the latest alert messages for a Vehicle.
      operationId: getVehicleTripAlerts
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/trips/{tid}/alerts/{aid}':
    get:
      security:
        - Vehicle_auth:
            - alert_read
            - Vehicle_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns information about a specific alert messages for a given Vehicle
        and Trip.
      operationId: getVehicleTripAlertByAid
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/trips/{tid}/collisions':
    get:
      security:
        - Vehicle_auth:
            - Collision_read
            - Vehicle_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns the set of Collisions that occurred for a given vehicle (id) and
        a speific Trip (tid) during the timestamp ranges and bounded by an index
        range.
      operationId: getVehicleCollisionsByTripId
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/trips/{tid}/collisions/{cid}':
    get:
      security:
        - Vehicle_auth:
            - Collision_read
            - Vehicle_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns the Collision(cid) that occurred for a given vehicle(id) during
        a Trip(tid) .
      operationId: getVehicleCollisionByTipById
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/trips/{tid}/ecoaching':
    get:
      security:
        - Vehicle_auth:
            - Trip_read
            - Vehicle_read
      tags:
        - Trips
      deprecated: true
      description: Return the Trip ECoaching evaluation.
      operationId: getTripsByVehicle
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/trips/{tid}/telemetry':
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns the set of Telemetry values that occurred for a given vehicle
        (id) and a speific Trip (tid) during the timestamp ranges and bounded by
        an index range.
      operationId: getTelemetryForTrip
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  '/user/vehicles/{id}/trips/{tid}/wayPoints':
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: Gives the Vehicle's wayPoints for a specified Trip.
      operationId: getPathForTrip
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
securityDefinitions:
  Vehicle_auth:
    authorizationUrl: 'https://api.mpsa.com/api/connectedcar/v2/oauth/authorize'
    flow: implicit
    scopes:
      Collision_read: read Collision related data
      Maintenance_read: read Maintenance related data
      Status_read: read Vehicle related status
      Telemetry_read: read Telemetry related data
      Trip_read: read Trip related data
      Vehicle_read: read Vehicle related data
      alert_read: read alert related data
      alert_write: 'create, modify or delete alerte'
      localisation_read: read location related data
    type: oauth2
tags:
  - name: User
  - description: Access to Vehicles details.
    name: Vehicles
  - description: Describe Trips of a a User or Vehicle
    name: Trips
x-components:
x-fragment:
  User_Trip_id_Alerts_getter:
    get:
      security:
        - Vehicle_auth:
            - alert_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: Returns the latest alert messages during a Trip.
      operationId: getUserTripAlerts
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  User_Trip_id_Alerts_id_getter:
    get:
      security:
        - Vehicle_auth:
            - alert_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: Returns information about a specific alert messages for a given Trip.
      operationId: getUserTripAlertByAid
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  User_Trip_id_Collisions_getter:
    get:
      security:
        - Vehicle_auth:
            - Collision_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns the set of Collisions that occurred for a given vehicle (id) and
        a speific Trip (tid) during the timestamp ranges and bounded by an index
        range.
      operationId: getUserCollisionsByTripId
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  User_Trip_id_Collisions_id_getter:
    get:
      security:
        - Vehicle_auth:
            - Collision_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns the Collision(cid) that occurred for a given vehicle(id) during
        a Trip(tid) .
      operationId: getUserCollisionByTipById
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  User_Trip_id_ECoaching_getter:
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: Return the User Trip ECoaching evaluation.
      operationId: getTripsByVehicle
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  User_Trip_id_Telemetry_getter:
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns the set of Telemetry values that occurred for a given vehicle
        (id) and a speific Trip (tid) during the timestamp ranges and bounded by
        an index range.
      operationId: getTelemetryForTrip
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  User_Trip_id_getter:
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        This method returns the Trip that matches the Trip id (tid) User has
        taken.
      operationId: getTripsByVehicle
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  User_Trip_id_wayPoints_getter:
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: Gives the wayPoints for a specified User Trip.
      operationId: getPathForTrip
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  User_Trips_getter:
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        This method returns a list of all Trips the User has taken. This will
        NOT include Trips that have not yet been completed.
      operationId: getUserTrips
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  Vehicle_id_Trip_id:
    get:
      security:
        - Vehicle_auth:
            - Trip_read
            - Vehicle_read
      tags:
        - Trips
      deprecated: true
      description: >-
        This method returns the Trip that matches the Trip id (tid) a given
        Vehicle (id) has taken.
      operationId: getTripByVehicle
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  Vehicle_id_Trip_id_Alerts_getter:
    get:
      security:
        - Vehicle_auth:
            - alert_read
            - Vehicle_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: Returns the latest alert messages for a Vehicle.
      operationId: getVehicleTripAlerts
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  Vehicle_id_Trip_id_Alerts_id_getter:
    get:
      security:
        - Vehicle_auth:
            - alert_read
            - Vehicle_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns information about a specific alert messages for a given Vehicle
        and Trip.
      operationId: getVehicleTripAlertByAid
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  Vehicle_id_Trip_id_Collisions_getter:
    get:
      security:
        - Vehicle_auth:
            - Collision_read
            - Vehicle_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns the set of Collisions that occurred for a given vehicle (id) and
        a speific Trip (tid) during the timestamp ranges and bounded by an index
        range.
      operationId: getVehicleCollisionsByTripId
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  Vehicle_id_Trip_id_Collisions_id_getter:
    get:
      security:
        - Vehicle_auth:
            - Collision_read
            - Vehicle_read
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns the Collision(cid) that occurred for a given vehicle(id) during
        a Trip(tid) .
      operationId: getVehicleCollisionByTipById
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  Vehicle_id_Trip_id_ECoaching_getter:
    get:
      security:
        - Vehicle_auth:
            - Trip_read
            - Vehicle_read
      tags:
        - Trips
      deprecated: true
      description: Return the Trip ECoaching evaluation.
      operationId: getTripsByVehicle
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  Vehicle_id_Trip_id_Telemetry_getter:
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: >-
        Returns the set of Telemetry values that occurred for a given vehicle
        (id) and a speific Trip (tid) during the timestamp ranges and bounded by
        an index range.
      operationId: getTelemetryForTrip
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  Vehicle_id_Trip_id_wayPoints_getter:
    get:
      security:
        - Vehicle_auth:
            - Trip_read
      tags:
        - Trips
      deprecated: true
      description: Gives the Vehicle's wayPoints for a specified Trip.
      operationId: getPathForTrip
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  Vehicle_id_Trips:
    get:
      security:
        - Vehicle_auth:
            - Trip_read
            - Vehicle_read
      tags:
        - Trips
      deprecated: true
      description: >-
        This method returns a list of all Trips that a given Vehicle has taken.
        This will NOT include Trips that have not yet been completed.
      operationId: getTripsByVehicle
      summary: OUT OF 1ST RELEASE (R-LEV 1.1) SCOPE
  general_error_fragment:
    schema:
      $ref: '#/definitions/xError'

